# Also can be set in env: TBD_APPKEY, TBD_SECRETKEY
#appkey: ""
#secretkey: ""

log:
  level: 1

chat:
  model: "ERNIE-Bot-4"
  color: "green"
  prompt: "# -> "

sync:
  notion:
    #db: "123"
    #token: "456"
  memos:
    host: "http://127.0.0.1:8081/"
    token: ""
